services:
  inferno:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
      - ./lib/:/opt/inferno/lib
      - ./:/opt/inferno/
    depends_on:
      validator-api-worker:
        condition: service_started
      redis:
        condition: service_started
      devbox-db:
        condition: service_healthy
    environment:
      TX_SERVER_URL: https://tx.dev.hl7.org.au/fhir
      POSTGRES_HOST: devbox-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: devbox
  inferno-worker:
    build:
      context: ./
    volumes:
      - ./data:/opt/inferno/data
    command: bundle exec sidekiq -r ./worker.rb
    depends_on:
      validator-api-worker:
        condition: service_started
      redis:
        condition: service_started
      devbox-db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: devbox-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: devbox
  nginx:
    image: nginx
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      validator-api:
        condition: service_started
      inferno:
        condition: service_started
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
  validator-api-worker:
    image: ghcr.io/beda-software/aidbox-validator/aidbox-validator:main-a5d15ca
    depends_on:
      validator-api:
        condition: service_healthy
    links:
      - validator-api
    env_file:
      - ./env/app
      - .env
    tty: true
  validator-api:
    image: healthsamurai/aidboxone:edge
    depends_on:
      devbox-db:
        condition: service_healthy
    links:
      - 'devbox-db:database'
    ports:
      - '127.0.0.1:8080:8080'
    env_file:
      - ./env/aidbox
      - .env
    volumes:
      - ./resources:/resources
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      interval: 1s
      timeout: 20s
      retries: 100
      test: curl --fail http://validator-api:8080/health || exit 1
  devbox-db:
    image: 'healthsamurai/aidboxdb:15.2'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  redis-data:
